language: python
python:
  - "3.7"

before_install:
  - python --version

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - pylint --version

script:
  - pylint *.py
